name: Coverage
run-name: Code Coverage

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  Discord-Node-Coverage:
    runs-on: ubuntu-latest
    environment: coverage
    timeout-minutes: 2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/jod
          cache: npm

      - name: Install Project Dependencies
        run: npm install

      - name: Create Environment Variables
        run: |
          touch .env
          echo CLIENT_TOKEN = ${{ secrets.BOT_TOKEN }} >> .env
          echo OLLAMA_IP = ${{ secrets.OLLAMA_IP }} >> .env
          echo OLLAMA_PORT = ${{ secrets.OLLAMA_PORT }} >> .env
          echo MODEL = ${{ secrets.MODEL }} >> .env

      - name: Run tests with coverage
        run: npm run coverage

      - name: Upload Coverage to Codecov
        id: codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/lcov.info
          fail_ci_if_error: true
        continue-on-error: true
