name: Deploy
run-name: Deploy Image and Restart Service
on:
  push:
    tags:
      - 'v*'

jobs:
  Deploy-Docker-Image:
    runs-on: ubuntu-latest
    environment: release
    timeout-minutes: 3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node Environment lts/jod
        uses: actions/setup-node@v4
        with:
          node-version: lts/jod
          cache: "npm"

      - name: Create Environment Variables
        run: |
          touch .env
          echo CLIENT_TOKEN = ${{ secrets.BOT_TOKEN }} >> .env
          echo OLLAMA_IP = ${{ secrets.OLLAMA_IP }} >> .env
          echo OLLAMA_PORT = ${{ secrets.OLLAMA_PORT }} >> .env
          echo REDIS_IP = ${{ secrets.REDIS_IP }} >> .env
          echo REDIS_PORT = ${{ secrets.REDIS_PORT }} >> .env

      - name: Get Version from package.json
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV
      
      - name: Build Image
        run: |
          npm run docker:build

        # Export Image to server somehow and restart it, otherwise deploy source code and build
        